In [1]:
%load_ext autoreload
%autoreload 2

In [4]:
import numpy as np
from bnb.problem import Problem

In [188]:
m = 2
n = 1
max_iter = np.inf
a_range = (-4.0, 4.0)
b_range = (0.001, 0.01)
epsilon = 0.01
seed = 1

problem = Problem(n, m, a_range, b_range, seed)
p = np.random.uniform(0, 1, size=n)

In [189]:
problem.revenue(p)

0.3958580130333753

In [190]:
problem.gradient(p)

array([0.01558738, 0.51937663, 0.06307975, 0.11855489, 0.21335298])

In [195]:
der = nd.Gradient(problem.revenue)

In [197]:
der(p)

array([0.01558738, 0.51937663, 0.06307975, 0.11855489, 0.21335298])

In [180]:
problem.B.shape

(2, 29)

In [181]:
p.shape

(29,)

In [182]:
p_.shape

(1, 29)

In [184]:
%%timeit

w_ = np.expand_dims(problem.w, axis=1)
p_ = np.expand_dims(p, axis=0)
b_ = np.expand_dims(problem.b, axis=0)

expU = np.exp(problem.A - problem.B * p_)
prob = expU / (1 + expU.sum(axis=1, keepdims=True))

grad = np.sum(
    (
        prob *
        w_ *
        (1 - p_ * b_ + b_ * np.sum(prob * p_, axis=1, keepdims=True))
    ),
    axis=0
)

27.3 µs ± 2.57 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [185]:
import numdifftools as nd

In [166]:
p_.shape

(1, 29)

In [171]:
np.sum(prob * p_, axis=1, keepdims=True)

array([[0.34780059],
       [0.61486143]])

In [167]:
w_.shape

(2, 1)

In [175]:
grad = np.sum(
    (
        prob *
        w_ *
        (1 - p_ * b_ + b_ * np.sum(prob * p_, axis=1, keepdims=True))
    ),
    axis=0
)

In [176]:
grad.shape

(29,)

In [163]:
p_.shape, b_.shape

((1, 29), (1, 29))

In [145]:
(prob * p_).shape

(2, 29)

In [137]:
prob.shape

(2, 29)

In [139]:
p_.shape

(29, 1)

In [117]:
grad.shape

(29,)

In [86]:
prob.shape

(2, 29)

In [7]:
A = np.asarray([segment.a for segment in problem.segments])
B = np.asarray([segment.b for segment in problem.segments])

In [53]:
problem.revenue(np.asarray([2.0]))

0.035479415207377435

In [73]:
a0, b0, p = problem.segments[0].a, problem.segments[0].b, np.asarray([2.0])
a1, b1, p = problem.segments[1].a, problem.segments[1].b, np.asarray([2.0])

In [74]:
problem.w[0] * p * np.exp(a0 - b0 * p) / (1 + np.exp(a0 - b0 * p))
problem.w[1] * p * np.exp(a1 - b1 * p) / (1 + np.exp(a1 - b1 * p))

array([0.12490185])

array([0.07072116])

In [76]:
problem.revenue(p)

0.19562301442142915

In [69]:
problem.w[0]

0.36666223123984704

In [51]:
_ = np.random.uniform(0, 1, size=(10, 2))

for __ in _:
    print(__)

[0.60632946 0.56885144]
[0.31736241 0.98861615]
[0.57974522 0.38014117]
[0.55094822 0.74533443]
[0.66923289 0.26491956]
[0.06633483 0.3700842 ]
[0.62971751 0.21017401]
[0.75275555 0.06653648]
[0.2603151  0.80475456]
[0.19343428 0.63946088]


In [48]:
%%timeit
expU = np.exp(self.A - self.B * p)
prob = expU / (1 + expU.sum(axis=1, keepdims=True))
rev = np.sum(np.sum(prob * p, axis=1) * self.w)

15.6 µs ± 27.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [42]:
rev

5.979113639076783

In [26]:
expU.sum(axis=1, keepdims=True).shape

(3, 1)

In [21]:
prob

array([[3.75451271e-04, 1.19634126e-03, 3.54593350e-02],
       [1.07905741e-01, 7.25628465e-03, 2.89121407e-02],
       [2.12691322e-04, 2.19891057e-04, 1.02711118e-01],
       [2.83833952e-03, 1.43029193e-02, 1.29863074e-02],
       [2.00746227e-01, 4.51996217e-04, 3.46960016e-02],
       [6.75136547e-03, 1.56744407e-02, 1.39901567e-03],
       [2.34314697e-02, 3.69769432e-02, 7.25166398e-04],
       [1.20848207e-03, 3.25328475e-04, 1.13577957e-01],
       [2.34157868e-02, 3.92362331e-03, 2.68127441e-03],
       [7.57730895e-02, 3.65654466e-02, 1.94341686e-01],
       [1.06350450e-04, 3.74071603e-03, 1.67830579e-02],
       [3.95111634e-02, 2.16150797e-04, 1.27962756e-02],
       [2.53013636e-01, 1.00030549e-02, 2.10279458e-04],
       [3.75516738e-02, 2.83298068e-02, 1.70113601e-01],
       [8.73595089e-04, 8.44510750e-03, 3.06720432e-03],
       [5.32443697e-02, 2.73302735e-01, 8.91677219e-03],
       [2.22534809e-04, 1.57544859e-02, 2.30890709e-03],
       [3.49344652e-03, 1.97970

In [12]:
from itertools import product



[[-1, -1, -1],
 [-1, -1, 1],
 [-1, 1, -1],
 [-1, 1, 1],
 [1, -1, -1],
 [1, -1, 1],
 [1, 1, -1],
 [1, 1, 1]]