In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
from bnb.problem import Problem

In [92]:
m = 2
n = 3
max_iter = np.inf
a_range = (-4.0, 4.0)
b_range = (0.001, 0.01)
epsilon = 0.01
seed = 1

problem = Problem(n, m, a_range, b_range, seed)


p_lb, p_ub = problem.p_lb, problem.p_ub
first_radius = np.max(p_ub - p_lb) / 2
first_cube_center = p_lb + radius
p = first_cube_center

radius = 0.1

In [219]:
from bnb.naive_optimizer import get_lipschitz_constant

def test_get_lipschitz_constant():
    
    lhs_vee = np.asarray([
        [0, 0, 1],
        [0, 0, 0]
    ])
    rhs_vee = - lhs_vee
    q_ub_r = np.asarray([
        [0.1, 0.5, 0.2],
        [0.1, 0.4, 0.9]
    ])
    b = np.asarray([0, 0, 1])
    w = np.asarray([0.2, 0.8])
    L = get_lipschitz_constant(lhs_vee, rhs_vee, q_ub_r, b, w)
    expectedL = w[0] * 0.2
    np.testing.assert_allclose(L, expectedL)
    
test_get_lipschitz_constant()
    
    

[0.   0.   0.04]


AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array(0.04)
 y: array(0.16)

In [214]:
M = np.asarray([[1, 2], [3, 4]])
np.max(M)

4

In [163]:
p_lb_local, p_ub_local = p - radius, p + radius

p_lb_r, p_ub_r = get_p_r(p, radius)
q_lb_r = get_q(p_lb_r, problem.A, problem.b)
q_ub_r = get_q(p_ub_r, problem.A, problem.b)


In [ ]:
p_ub_local = p + radius
p_lb_r, p_ub_r = get_p_r(p, radius)
q_lb_r = get_q(p_lb_r, A, b)
q_ub_r = get_q(p_ub_r, A, b)
rhs_vee = p_ub_local * (1 - q_lb_r)
lhs_vee = get_lhs_vee(q_ub_r, p_ub_r, b)

In [ ]:


# p_q_ub = (
#     np.repeat(np.expand_dims(q_ub_r, axis=1), n, axis=1)
#     * p_ub_r
#     * problem.b
# )



# lhs_of_vee = 1 + np.sum(p_q_ub, axis=2)
# rhs_of_vee = (
#     problem.b
#     * p_ub_r
#     * (1 - np.repeat(np.expand_dims(q_ub_r, axis=1), n, axis=1))
# )


array([0.06616447, 0.26650905, 0.12573765])

In [162]:
p_ub_r

array([[998.97168516, 268.9454555 , 431.0853412 ],
       [999.17168516, 268.7454555 , 431.0853412 ],
       [999.17168516, 268.9454555 , 430.8853412 ]])

In [159]:
lhs_of_vee

array([[1.11895668, 1.10521558, 1.03825632],
       [1.37459294, 1.19077725, 1.35750237]])

In [161]:
q_ub_r

array([[0.01225516, 0.02597938, 0.09291484],
       [0.08682596, 0.27045775, 0.10388569]])

In [151]:
p_q_ub[0, 0, :]

array([[[0.        , 0.02599871, 0.09295797],
        [0.01225761, 0.        , 0.09295797],
        [0.01225761, 0.02599871, 0.        ]],

       [[0.        , 0.27065903, 0.10393391],
        [0.08684334, 0.        , 0.10393391],
        [0.08684334, 0.27065903, 0.        ]]])

In [154]:
np.sum(p_q_ub[0, 0, :])

0.11895667944503

In [135]:
M = np.asarray([
    [[1, 2], [3, 4]],
])



(1, 2, 2)

In [136]:
M

array([[[1, 2],
        [3, 4]]])

In [137]:
M * np.asarray([100, 200])

array([[[100, 400],
        [300, 800]]])

In [127]:
p_q_ub.shape

(2, 3, 3)

In [110]:
q_ub_r.shape

(2, 3)

In [211]:




 
test_get_q()
test_get_p_r()

In [116]:
get_q(p, problem.A, problem.b)

array([[0.01256473, 0.02766329, 0.09441883],
       [0.09412336, 0.30401456, 0.12205388]])

In [112]:
exp_utilities.shape

(2, 3, 3)

In [111]:
(exp_utilities / (1 + np.sum(exp_utilities, axis=2, keepdims=True))).shape

(2, 3, 3)

In [110]:
problem.A.shape

(2, 3)

In [108]:
p_lb_r * problem.b

array([[1.23287418, 1.        , 1.        ],
       [1.        , 1.86563216, 1.        ],
       [1.        , 1.        , 1.53989934]])

In [106]:
problem.b

array([0.00100103, 0.00372099, 0.0023208 ])

In [107]:
p_ub_r

array([[ 998.97168516,  501.38016589,  663.52005159],
       [1231.60639555,  268.7454555 ,  663.52005159],
       [1231.60639555,  501.38016589,  430.8853412 ]])

array([[[0.00000000e+000, 6.87068168e-220, 2.63355365e-290],
        [0.00000000e+000, 1.56779028e-118, 5.58289280e-290],
        [0.00000000e+000, 5.20935106e-219, 2.14929976e-188]],

       [[0.00000000e+000, 7.84682718e-219, 3.00771326e-289],
        [0.00000000e+000, 2.63144797e-117, 9.37057212e-289],
        [0.00000000e+000, 9.38887606e-219, 3.87370880e-188]]])

In [89]:
q_bar

array([[1., 1., 1.],
       [1., 1., 1.]])

In [81]:
exp_utilities.shape

(2, 3, 3)

In [52]:
p_ub_r * problem.b + problem.segments[0].a

array([[-2.26129124, -0.64428614,  0.30438515],
       [-2.02841706, -1.50991831,  0.30438515],
       [-2.02841706, -0.64428614, -0.23551418]])

In [40]:
p_lb_r[0]

array([1231.60639555,  268.7454555 ,  430.8853412 ])

In [36]:
p

array([1115.28904036,  385.0628107 ,  547.2026964 ])

In [33]:
radius

116.31735519527359

In [62]:
A = np.asarray([[1, 2], [3, 4]])

np.repeat(
    np.expand_dims(A, axis=0),
    3,
    axis=0
)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [45]:
np.asarray([100, 1]) * np.asarray([[1, 2], [3, 4]]) + problem.segments[0].a

array([[100,   2],
       [300,   4]])